"""
Pune city config, the reference implementation of CityConfig and the v1
validation city (ground truth: Wakad/Hinjewadi/Kharadi are known-good
corridors, see CLAUDE.md kickoff brief).

10 corridors as of 2026-07-05 (user-specified list, DECISIONS.md):
Hinjewadi, Wakad, Baner, Kharadi, Hadapsar, Magarpatta Road, Viman Nagar,
Balewadi, Ambegaon, Undri. The earlier Koregaon Park/Wagholi/Katraj entries
were dropped entirely (not just deprioritized) per user decision - Ambegaon
and Undri now serve as the real known-weak/ineligible examples instead.

`corridor_candidates` metrics (price band, comp density, etc) below are
SEED / PLACEHOLDER numbers, not yet computed from live data. They exist to
prove the scoring engine end-to-end before the RERA + comp pipeline
(Milestone 2+) produces real numbers in this same shape.

`canonical_societies` are REAL for all 10 corridors, pulled from live
MagicBricks scrapes: Hinjewadi (2026-07-03/05, 149 names from a 600-listing
sample) and the other 9 (2026-07-05, 30 listings each, 1 page). Placeholder
"<Name> Society Seed 0X" entries have been fully replaced - see DECISIONS.md
2026-07-05.
"""

from config.city_config import (
    CityConfig,
    CorridorCandidate,
    DemandAnchor,
    ListingSourceConfig,
    RERASource,
)

PUNE = CityConfig(
    city_id="pune",
    city_name="Pune",
    state="Maharashtra",
    rera_source=RERASource(
        name="MahaRERA",
        url="https://maharera.mahaonline.gov.in/",
        note="Project-level registration and complaint status lookup.",
    ),
    # Rs 75L-1.55Cr, the same band already locked in scoring/society_config.py
    # (2026-07-03 Plan Mode decision). Duplicated here as literal values
    # rather than imported, since config/ is upstream of scoring/ in this
    # codebase's dependency direction (scoring imports config, never the
    # reverse) - see scoring/society_fit.py for the city-agnostic consumer.
    product_price_band_min_inr=7_500_000,
    product_price_band_max_inr=15_500_000,
    demand_anchors=[
        DemandAnchor(name="Hinjewadi IT Park (Phase 1-3)", lat=18.5913, lon=73.7389),
        DemandAnchor(name="EON IT Park, Kharadi", lat=18.5510, lon=73.9330),
        DemandAnchor(name="Magarpatta / Hadapsar IT Park", lat=18.5158, lon=73.9280),
    ],
    listing_sources=[
        ListingSourceConfig(
            source="99acres",
            active=False,
            note="Blocked by Akamai bot protection (403 on first page load, recon 2026-07-03).",
        ),
        ListingSourceConfig(
            source="magicbricks",
            active=True,
            note="Server-rendered, not blocked. Primary v1 source.",
        ),
        ListingSourceConfig(
            source="nobroker",
            active=False,
            note="Not blocked, but listings are client-rendered via internal JSON APIs "
            "(no locality filter reproduced yet). Deferred to v1.5.",
        ),
    ],
    corridor_candidates=[
        CorridorCandidate(
            name="Hinjewadi",
            pct_units_in_band=0.58,
            min_distance_to_demand_anchor_km=0.8,
            rera_clean_pct=0.82,
            comp_count_90d=55,
            avg_dom_days=38,
            resale_txn_count_90d=40,
            # Real society names observed across THREE live MagicBricks scrapes
            # (2026-07-03 x30, 2026-07-05 x30, 2026-07-05 x600 across 20
            # pages, see DECISIONS.md). Each scrape surfaced a largely
            # different set of active listings - this is a live, moving
            # marketplace, not a static list. Confirms the entity-resolution
            # risk flagged in the original Phase 1 pushback: a scrape-derived
            # canonical list is a moving target. The durable fix is sourcing
            # canonical names from MahaRERA (city config's rera_source)
            # instead of accumulating them scrape by scrape, deferred past
            # v1 (Layer 2C blocked/paused, see PROGRESS.md).
            canonical_societies=[
                "32 Pinewood Drive",
                "64 Green Meadows",
                "Achalare Citrine",
                "Air Castles",
                "Arihanta Aastha",
                "Ashiana Malhar",
                "Aspiria",
                "Basera Eternity",
                "Beverly Hills",
                "Blueridge slim fit and NGA Towers",
                "Candy Floors",
                "Eiffel Xrbia",
                "GLOBAL INSPIRA",
                "Geeta Prem Mairah Residences",
                "Gera Adara",
                "Geras Joy on the Treetops",
                "Global Lifestyle",
                "Godrej 24",
                "Godrej Elements",
                "Godrej Evergreen Square",
                "Godrej Woodsville",
                "Grand Avenue",
                "Gurukrupa Residency",
                "HS Lagom Homes",
                "High Mount Phase 2",
                "Hinjawadi Building D1 Eon Homes",
                "Hinjewadi IT Park",
                "Icon Viva",
                "Javdekar Yashwin Phase II",
                "Jhamtani Ace Augusta",
                "Joy on The Tree Tops Project A",
                "Kalpataru Splendour",
                "Kasturi Apostrophe",
                "Kasturi Apostrophe Hinjawadi Tower C",
                "Kasturi Eon Homes",
                "Kohinoor Central Park",
                "Kohinoor Coral",
                "Kohinoor Famville",
                "Kohinoor Sportsville",
                "Kohinoor Tinsel County",
                "Kohinoor Tinsel Town",
                "Kolte Patil Duet",
                "Kolte Patil Green Olive",
                "Kolte Patil I Ven Township",
                "Kolte Patil Life Republic",
                "Kolte Patil Life Republic Arezo",
                "Kolte Patil Life Republic Aros",
                "Kolte Patil Life Republic R16",
                "Kolte Patil Life Republic Sector R16 16th Avenue Arezo F Building",
                "Kolte Patil Life Republic Sector R7 7th Avenue I Towers",
                "Kolte Patil Life Republic Universe Phase I",
                "Kolte Patil Life Republic Universe Phase III",
                "Kolte-Patil Life Republic Oro Avenue",
                "Krishna Amarillo",
                "Kul Ecoloch Phase I",
                "Kumar Megapolis Saffron",
                "Kumar Megapolis Splendour",
                "Life Republic Clubhouse",
                "Life Republic I Tower",
                "Life Republic Sector R22 22nd Avenue Atmos Phase II",
                "Lodha Magnus",
                "Lodha Panache",
                "Lodha Sylvan",
                "MP Residency",
                "Mega Polis Splendour and Sparklet Smart Homes",
                "Megapolis Sangria Towers",
                "Megapolis Smart Homes I",
                "Megapolis Sparklet",
                "Megapolis Splendour Smart Homes III",
                "Megapolis Sunway",
                "Menlo Homes Hinjewadi",
                "Mittal Highmont Phase 1",
                "Mittal Sky High Towers",
                "Paranjape Athashri Xion",
                "Paranjape Blue Ridge",
                "Paranjape Blueridge The Groves",
                "Paranjape Orion at Blue Ridge",
                "Paranjape The Groves",
                "Paranjape The Lofts",
                "Paras Delicia",
                "Parth Kiona",
                "Pashankar Guruprasad",
                "Pegasus Megapolis",
                "Pegasus Megapolis Mystic",
                "Pegasus Megapolis Saffron A10 To A14",
                "Pegasus Megapolis Serenity",
                "Pegasus Megapolis Springs",
                "Pegasus Megapolis Springs Phase 3",
                "Peninsula Ashok Meadows",
                "Pragati Apartment",
                "Pride Park Astra",
                "Pride Park Titan",
                "Pride Purple Park Connect",
                "Pride Purple Park Titan",
                "R7 LIFE REPUBLIC",
                "Rahul Aston",
                "Rama Fusion Towers",
                "Rama Melange Residences",
                "Rama Melange Residences Phase III",
                "Redshift Bloomville",
                "Rohan Ipsita",
                "Rohan Prathama",
                "SRS You 57",
                "Saarrthi Savvy Homes II",
                "Saffron",
                "Sagar Accord",
                "Saheel ITrend Homes",
                "Saheel Landmarc",
                "Seetai Villa",
                "Shapoorji Pallonji Joyville",
                "Shapoorji Pallonji Joyville Hinjewadi",
                "Shapoorji Pallonji Sensorium",
                "Shapoorji Pallonji Sensorium Phase II",
                "Size Dew Drops Hinjewadi",
                "Sovereign",
                "Spring Woods",
                "Srinath Megapolis Symphony Phase I",
                "Stone Bappa Residency",
                "Sun Residency",
                "TCG The Cliff Garden",
                "TCG The Crown Greens",
                "TCG The Crown Greens Phase 2",
                "The Aqua Retreat at Godrej Park World",
                "The Gale at Godrej Park World",
                "The Greenfront at Godrej Park World",
                "The Legend",
                "The Ridges 41",
                "VJ One Avenue",
                "VTP Bellissimo",
                "VTP MONARQUE",
                "VTP Volare",
                "Vasant Avenue",
                "Vasant Utsav",
                "Vascon Xotech",
                "Viijcon Cellandine",
                "Vikas Javdekar Yashone Maan",
                "Vilas Javdekar YashOne Eternitee",
                "Vilas Javdekar Yashone Hinjewadi Phase 1",
                "Vilas Javdekar Yashwin Hinjewadi",
                "Vilas Javdekar Yashwin Yashwin Sukhniwas",
                "Village Residency 1",
                "Village Residency 3",
                "Vision Eternity",
                "Welworth Purnam",
                "West Wind Park",
                "Xrbia Hinjewadi",
                "Xrbia Sneh Properties",
                "Xrbia Township",
            ],
        ),
        CorridorCandidate(
            name="Wakad",
            pct_units_in_band=0.62,
            min_distance_to_demand_anchor_km=2.5,
            rera_clean_pct=0.85,
            comp_count_90d=48,
            avg_dom_days=42,
            resale_txn_count_90d=35,
            # Real society names, live MagicBricks scrape (2026-07-05, 30 listings).
            canonical_societies=[
                "Alliance Nisarg II",
                "Aswani Galaxy",
                "Atharva Galaxy",
                "Balaji Oriana Crest",
                "GK Atlanta Phase 1",
                "Gauree Space Star Woods",
                "Kalpataru Crescendo",
                "Kohinoor Courtyard One",
                "Kolte Patil City Avenue",
                "Mont Vert Oystera",
                "Nisarg Vishwa",
                "Paramount Madhupushpa Phase 1 CHS",
                "Pride Park Ivory",
                "Rajashree Enclave",
                "Royal Entrada",
                "Sai Arcade",
                "Signature Heights",
                "Sonigara Omega Paradise",
                "Suyog Space",
                "Vardhaman Dreams Phase II",
                "Vilas Javdekar Yashwin Supernova",
                "Vishal Skyscraper",
                "Zinnia Elegans",
            ],
        ),
        CorridorCandidate(
            name="Kharadi",
            pct_units_in_band=0.55,
            min_distance_to_demand_anchor_km=1.5,
            rera_clean_pct=0.80,
            comp_count_90d=50,
            avg_dom_days=45,
            resale_txn_count_90d=32,
            # Real society names, live MagicBricks scrape (2026-07-05, 30 listings).
            canonical_societies=[
                "ARV Uthville",
                "Duville Riverdale Heights",
                "Gera Planet Of Joy",
                "Gera World of Joy",
                "Geras Song Of Joy Geras Greenville",
                "Gulmohar Coast",
                "Kohinoor Zen Estate",
                "Matrix Infra Alfa 1",
                "Mountain Glory",
                "Palm World One",
                "Pearl Paradise",
                "Pegasus",
                "Pristine Meadows",
                "Unique Youtopia",
                "Vandana Residency",
                "Vascon Forest Edge",
                "Vilas Javdekar Yashwin Orizzonte",
                "Vishal Leela Residency",
            ],
        ),
        CorridorCandidate(
            name="Baner",
            pct_units_in_band=0.40,
            min_distance_to_demand_anchor_km=4.0,
            rera_clean_pct=0.83,
            comp_count_90d=38,
            avg_dom_days=50,
            resale_txn_count_90d=25,
            # Real society names, live MagicBricks scrape (2026-07-05, 30 listings).
            canonical_societies=[
                "ABIL Imperial Atria",
                "Aldea Espanola Phase 2",
                "Atul Westernhills",
                "Aurum Sanskruti Allure",
                "Balaji Housing Society",
                "GM Freshia Apartment",
                "Ganga Acropolis",
                "Green Leaf",
                "Harshville Veerbhadra Nagar",
                "Kedar Atharva",
                "Manohar Bliss",
                "Mohan Nagar CHS",
                "Mont Vert Biarritz",
                "Nandan Prospera Gold",
                "Prithvi Residency",
                "Purushottam Vihar",
                "Shivashakti Complex",
                "Shree Samarth 66 Gulmohar",
                "Shriram Chandrama",
                "The Creations Gururatna Heritage",
                "Unique Classic",
                "VTP Skylights Verve",
                "VTP Solitaire",
                "Vilas Prime Panache C Wing",
                "Whitewater House",
            ],
        ),
        CorridorCandidate(
            name="Hadapsar",
            pct_units_in_band=0.50,
            min_distance_to_demand_anchor_km=1.8,
            rera_clean_pct=0.78,
            comp_count_90d=35,
            avg_dom_days=48,
            resale_txn_count_90d=28,
            # Real society names, live MagicBricks scrape (2026-07-05, 30 listings).
            canonical_societies=[
                "Bhandari Greenfield Phase I",
                "Dreams Aakruti Plot No 2 BLDG DE CHSL",
                "Eisha Empire",
                "Kumar Codename Fireworks",
                "Marvel Arco",
                "Moreshwar Apartment",
                "Navratna Exotica",
                "Pawar Heights",
                "Sai Leisure Town",
                "Simpli City Phase II",
                "Ved Vihar",
                "Well Wisher Kiara Terrezo",
                "Wellwisher Kiarah Terrazo",
            ],
        ),
        CorridorCandidate(
            name="Magarpatta Road",
            pct_units_in_band=0.35,
            min_distance_to_demand_anchor_km=1.0,
            rera_clean_pct=0.85,
            comp_count_90d=40,
            avg_dom_days=35,
            resale_txn_count_90d=30,
            # Real society names, live MagicBricks scrape (2026-07-05, 30
            # listings). URL slug is "magarpatta-road", not "magarpatta" -
            # bare "magarpatta" 404s on MagicBricks (recon 2026-07-05,
            # DECISIONS.md). "Magarpatta City" is a narrower, separate,
            # pricier locality slug on the same site.
            canonical_societies=[
                "A And A Breeza",
                "Bhandari Greenfield Phase I",
                "Dreams Aakruti Plot No 2 BLDG DE CHSL",
                "Godrej Infinity",
                "Kumar Codename Fireworks",
                "Marvel Arco",
                "Navratna Exotica",
                "Polaris",
                "Puravankara Purva Silversands",
                "Sai Leisure Town",
                "Sancheti Associates Belcastel",
                "Simpli City Phase II",
                "Vastushree Adrina Phase 1",
                "Venkatesh Graffiti Phase 7",
                "Well Wisher Kiara Terrezo",
                "Wellwisher Kiarah Terrazo",
            ],
        ),
        CorridorCandidate(
            name="Viman Nagar",
            pct_units_in_band=0.45,
            min_distance_to_demand_anchor_km=3.5,
            rera_clean_pct=0.80,
            comp_count_90d=32,
            avg_dom_days=45,
            resale_txn_count_90d=27,
            # Real society names, live MagicBricks scrape (2026-07-05, 30 listings).
            canonical_societies=[
                "ARK Prem Alfa Premio",
                "Ambar Zenith",
                "Camelot Royale",
                "Clover Acropolis",
                "Eden Garden",
                "Elegant Heritage",
                "Hermes Drome",
                "Konark Campus",
                "Lunkad Amazon",
                "Lunkad Gold Coast",
                "Lunkad Sky Vie",
                "Oxy Beaumonde",
                "Rohan Mithila",
                "Shubh Gateway",
                "Shubh Nirvana",
                "Siddhesh Optimus",
                "Viman Pride",
            ],
        ),
        CorridorCandidate(
            name="Balewadi",
            pct_units_in_band=0.48,
            min_distance_to_demand_anchor_km=3.0,
            rera_clean_pct=0.81,
            comp_count_90d=30,
            avg_dom_days=46,
            resale_txn_count_90d=24,
            # Real society names, live MagicBricks scrape (2026-07-05, 30 listings).
            canonical_societies=[
                "ANP Universe",
                "Aditya Comfort Zone",
                "Aditya Shagun Comfort Zone Plus",
                "Atharva Prima Domus",
                "Bhandari Aura",
                "Gini Viviana",
                "Imperium",
                "Kunal The Canary",
                "Nahar F Residences",
                "Naiknavare Avon Vista",
                "Paradigm Imperial Woods",
                "Paritosh",
                "Shagun Perfect 10",
                "Sharada Paritosh",
                "Shreemant Ganaray Krupa",
                "Utsav 51 Balewadi Residences",
                "Vatika Homes",
                "Wonderwall",
            ],
        ),
        CorridorCandidate(
            name="Ambegaon",
            pct_units_in_band=0.68,
            min_distance_to_demand_anchor_km=11.0,
            rera_clean_pct=0.65,
            comp_count_90d=20,
            avg_dom_days=75,
            resale_txn_count_90d=15,
            # Real society names, live MagicBricks scrape (2026-07-05, 30
            # listings). Peripheral/budget corridor, far from all 3 demand
            # anchors - fails the demand_adjacent, clean_title, comp_density
            # and resale_velocity gates. A real known-weak example now,
            # replacing the fictional Koregaon Park/Wagholi/Katraj entries.
            canonical_societies=[
                "Amit Astonia Royale",
                "Amits Bloomfield Phase III J And K Building",
                "Bliss Coast",
                "Bright Side",
                "Chaandrai Meghsparsh",
                "Dhavel Nilayam",
                "Forest Castle",
                "Grandeur Emerald",
                "Guardian Lake Shire",
                "Hemant Sunville",
                "Kool Homes Panchamrut",
                "Navjeevan Sundarban",
                "Om Praangan",
                "Sai Enclave",
                "Sai Samarth Apartment",
                "Sai Sarovar",
                "Sai Shraddha",
                "Shivdatta Royal",
                "Shri Venkatesh Meghsparsh Phase II",
                "Sun View",
                "Swaroop Society",
                "Trimurti Heights",
                "Venkatesh Lake Life",
                "Venkatesh Sharada Megh Sparsh",
            ],
        ),
        CorridorCandidate(
            name="Undri",
            pct_units_in_band=0.72,
            min_distance_to_demand_anchor_km=13.0,
            rera_clean_pct=0.60,
            comp_count_90d=17,
            avg_dom_days=85,
            resale_txn_count_90d=10,
            # Real society names, live MagicBricks scrape (2026-07-05, 30
            # listings). Peripheral/budget corridor, same profile as
            # Ambegaon - fails multiple gates, a second real known-weak
            # example.
            canonical_societies=[
                "38 Park Majestique",
                "Atria Dhanashree Aangan",
                "Atria Dhanashree Aashiyana",
                "Bliss Society",
                "El Regalo",
                "Ganga Glitz Crest",
                "Godrej Horizon",
                "Kailash Kanchan",
                "Niyati Niyati Apartments",
                "Shreemangal Vishhram Little Hearts",
                "Shreeya Avenue",
                "Swami Samruddhi",
            ],
        ),
    ],
)
